name: My Workflow

on: workflow_dispatch

concurrency:
  group: build-push-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DIFY_WEB_IMAGE_NAME: 'langgenius/dify-web'
  DIFY_API_IMAGE_NAME: 'langgenius/dify-api'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        include:
          # - service_name: "build-api-amd64"
          #   image_name_env: "DIFY_API_IMAGE_NAME"
          #   context: "api"
          #   platform: linux/amd64
          - service_name: "build-web-amd64"
            image_name_env: "DIFY_WEB_IMAGE_NAME"
            context: "web"
            platform: linux/amd64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env[matrix.image_name_env] }}

      - name: Build Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: false
          context: "{{defaultContext}}:${{ matrix.context }}"
          platforms: ${{ matrix.platform }}
          build-args: COMMIT_SHA=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=gha,scope=${{ matrix.service_name }}
          # cache-to: type=gha,mode=max,scope=${{ matrix.service_name }}
          tags: dify-web:0.15.3-custom
          outputs: type=docker

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          docker save -o /tmp/digests/dify_web_custom.tar dify-web:0.15.3-custom
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

